image: archlinux
environment:
  PATH: $HOME/go/bin:/usr/local/sbin:/usr/local/bin:/usr/bin
packages:
  - curl
  - go
  - golangci-lint
  - just
  - postgresql
  - postgresql-libs
  - staticcheck
  - sudo
tasks:
  - services: |
      pushd grokloc-go
      sudo just initdb
      sudo systemctl start postgresql.service
  - setup: |
      pushd grokloc-go
      just ci-setup
  - test: |
      pushd grokloc-go
      just vendor test lint
