image: archlinux
environment:
  PATH: $HOME/go/bin:/usr/local/sbin:/usr/local/bin:/usr/bin
tasks:
  - arch: |
      sudo pacman -Syu --noconfirm
      sudo pacman -S --noconfirm curl go golangci-lint just postgresql postgresql-libs staticcheck
  - services: |
      pushd grokloc-go
      sudo just initdb
      sudo systemctl start postgresql.service
  - setup: |
      pushd grokloc-go
      just ci-setup
  - test: |
      pushd grokloc-go
      just vendor test lint
